services:
    
    o-auth:
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app:/code
        ports:
            - 8022:8000
        env_file:
            - ./app/.env
        depends_on:
            - o-auth-db

    o-auth-db:
        image: mysql:8.0.31  
        restart: always
        env_file:
            - ./app/.env
        ports:
            - 3312:3306
        volumes:
            - o-auth-db:/var/lib/mysql

volumes:
    o-auth-db: