name: Build, Test and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker-username: ${{ steps.set-env.outputs.DOCKER_USERNAME }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment variables
        id: set-env
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
        outputs:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          
      - name: Build o-auth Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/o-auth:latest ./app

      - name: Build o-auth-db Docker image
        run: |
          docker pull mysql:8.0.31
          docker tag mysql:8.0.31 ${{ secrets.DOCKER_USERNAME }}/o-auth-db:latest

      - name: Push o-auth Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/o-auth:latest

      - name: Push o-auth-db Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/o-auth-db:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml run o-auth pytest app/tests/
