name: Build, Test and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build o-auth Docker image
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/o-auth:latest ./app

      - name: Build o-auth-db Docker image
        run: |
          docker pull mysql:8.0.31
          docker tag mysql:8.0.31 ${{ env.DOCKER_USERNAME }}/o-auth-db:latest

      - name: Push o-auth Docker image
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/o-auth:latest

      - name: Push o-auth-db Docker image
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/o-auth-db:latest

  test:

    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep '\"tag_name\"' | sed -E 's/.*"([^"]+)".*/\1/')" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start services with Docker Compose
        run: |
          docker-compose -f ./app/docker-compose.yml up -d

      - name: Run migrations inside container
        run: |
          docker exec o-auth python manage.py migrate

      - name: Run tests inside container
        run: |
          docker exec o-auth pytest app/tests/

      - name: Clean up containers
        run: |
          docker-compose -f docker-compose.yml down
