# Workflow name: Build and Push Docker Image
# Description: This GitHub Actions workflow builds a Docker image from the code in the 'main' branch and pushes it to Docker Hub.

name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build o-auth Docker image
        run: |
          docker build -t $DOCKER_USERNAME/o-auth:latest ./app
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Build o-auth-db Docker image
        run: |
          docker pull mysql:8.0.31
          docker tag mysql:8.0.31 $DOCKER_USERNAME/o-auth-db:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Push o-auth Docker image
        run: |
          docker push $DOCKER_USERNAME/o-auth:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Push o-auth-db Docker image
        run: |
          docker push $DOCKER_USERNAME/o-auth-db:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      o-auth-db:
        image: $DOCKER_USERNAME/o-auth-db:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s
      o-auth:
        image: $DOCKER_USERNAME/o-auth:latest
        ports:
          - 8000:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run migrations inside container
        run: |
          docker-compose run o-auth python manage.py migrate

      - name: Run tests inside container
        run: |
          docker-compose run o-auth pytest app/tests/
